system:
  DesignTarget: cache
  Capacity: 
    - Value: 8
      Unit: MB
    - Value: 16
      Unit: MB
  WordWidth: 128 # bits
  OptimizationTarget: WriteEDP

apps:
  run: existing
  profiler: sniper
  multithread: false
  patternconfig_path: configs/spec_2017_sniper_config/pattern_configs


tech:
  run: existing
  array_characterization_result_path: configs/spec_2017_sniper_config/FeFet_data
