# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timeseries_metrics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18timeseries_metrics.proto\x12\x11memsys.timeseries\"t\n\x0eTimeSeriesData\x12\x30\n\x08metadata\x18\x01 \x01(\x0b\x32\x1e.memsys.timeseries.RunMetadata\x12\x30\n\x07samples\x18\x02 \x03(\x0b\x32\x1f.memsys.timeseries.SampleWindow\"\xa0\x01\n\x0bRunMetadata\x12\x10\n\x08profiler\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\r\x12\x17\n\x0fstart_timestamp\x18\x03 \x01(\x04\x12\x0f\n\x07\x63ommand\x18\x04 \x01(\t\x12\x1a\n\x12sample_window_refs\x18\x05 \x01(\r\x12\x17\n\x0f\x63\x61\x63he_line_size\x18\x06 \x01(\r\x12\x13\n\x0bnum_threads\x18\x07 \x01(\r\"\xaf\x01\n\x0cSampleWindow\x12\x15\n\rwindow_number\x18\x01 \x01(\x04\x12\x11\n\tthread_id\x18\x02 \x01(\r\x12\x12\n\nread_count\x18\x03 \x01(\x04\x12\x13\n\x0bwrite_count\x18\x04 \x01(\x04\x12\x12\n\ntotal_refs\x18\x05 \x01(\x04\x12\x11\n\twss_exact\x18\x06 \x01(\x04\x12\x12\n\nwss_approx\x18\x07 \x01(\x01\x12\x11\n\ttimestamp\x18\x08 \x01(\x04\x42\x03\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timeseries_metrics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _TIMESERIESDATA._serialized_start=47
  _TIMESERIESDATA._serialized_end=163
  _RUNMETADATA._serialized_start=166
  _RUNMETADATA._serialized_end=326
  _SAMPLEWINDOW._serialized_start=329
  _SAMPLEWINDOW._serialized_end=504
# @@protoc_insertion_point(module_scope)
