MemoryCell:
  MemoryCellType: SRAM
  CellArea_F2: 146
  CellArea_um2: 0.149504
  AspectRatio: 1.46
  WidthAccessCMOS_F: 1.31
  WidthSRAMCellNMOS_F: 2.08
  WidthSRAMCellPMOS_F: 1.23
  PeripheralRoadmap: LOP
  PeripheralNode_nm: 32
  VDD_V: 0.9
  Temperature_K: 370
CacheDesign:
  AccessMode: Normal
  DesignTarget: Cache
  OptimizationTarget: WriteDynamicEnergy
  Area:
    Total_mm2: 12.543418951652773
    DataArray_mm2: 10.150097872936932
    TagArray_mm2: 2.393321078715842
  Timing:
    CacheHitLatency_ns: 76.04590370167864
    CacheMissLatency_ns: 59.038256263086254
    CacheWriteLatency_ns: 58.83367326025146
    Reset:
      PulseDuration_ns: 0
    Set:
      PulseDuration_ns: 0
  Power:
    CacheHitDynamicEnergy_nJ: 0.6777336666880502
    CacheMissDynamicEnergy_nJ: 0.6777336666880502
    CacheWriteDynamicEnergy_nJ: 0.013203417631976836
    CacheTotalLeakagePower_mW: 13.005517511064806
    CacheDataArrayLeakagePower_mW: 10.349605895863313
    CacheTagArrayLeakagePower_mW: 2.6559116152014948
Capacity:
  Value: 8
  Unit: MB
DataArray:
  Configuration:
    BankOrganization:
      Rows: 1
      Columns: 1
      RowActivation: 1
      TotalRows: 1
      ColumnActivation: 1
      TotalColumns: 1
    MatOrganization:
      Rows: 2
      Columns: 2
      RowActivation: 1
      TotalRows: 2
      ColumnActivation: 1
      TotalColumns: 2
      SubarrayRows: 4096
      SubarrayColumns: 4096
    MuxLevels:
      SenseampMux: 4
      OutputLevel1Mux: 1
      OutputLevel2Mux: 1
      RowsPerSet: 1
    LocalWire:
      WireType: LocalAggressive
      RepeaterType: NoRepeaters
      LowSwing: No
    GlobalWire:
      WireType: GlobalAggressive
      RepeaterType: NoRepeaters
      LowSwing: No
    BufferDesignStyle: LatencyOptimized
  Results:
    Area:
      Total:
        Height_um: 3852.256256739998
        Width_um: 2634.844931506849
        Area_mm2: 10.150097872936932
      Mat:
        Height_um: 3852.256256739998
        Width_um: 2634.844931506849
        Area_mm2: 10.150097872936932
        Efficiency_percent: 98.84676708593096
      Subarray:
        Height_um: 1919.2161999999998
        Width_um: 1317.4224657534246
        Area_mm2: 2.5284185385179176
        Efficiency_percent: 99.20275708523585
      AreaEfficiency_percent: 98.84676708593096
    Timing:
      Read:
        Latency_ns: 42.313060080183455
        TreeLatency_ns: 0
        MatLatency_ns: 42.313060080183455
        PredecoderLatency_ns: 1.3899615644093983
        SubarrayLatency_ns: 40.92309851577406
        RowDecoderLatency_ns: 24.632594996776657
        BitlineLatency_ns: 16.190223762000247
        SenseampLatency_ns: 0.006900422320347003
        MuxLatency_ns: 0.09337933467680676
        PrechargeLatency_ns: 30.558253889927336
      Write:
        Latency_ns: 42.313060080183455
        TreeLatency_ns: 0
        MatLatency_ns: 42.313060080183455
        PredecoderLatency_ns: 1.3899615644093983
        SubarrayLatency_ns: 40.92309851577406
        RowDecoderLatency_ns: 24.632594996776657
        BitlineLatency_ns: 16.190223762000247
      ReadBandwidth_Bps: 341524533.0915006
      WriteBandwidth_Bps: 390977237.3133648
    Power:
      Read:
        DynamicEnergy_pJ: 545.0404202046327
        TreeDynamicEnergy_pJ: 0
        MatDynamicEnergy_pJ: 545.0404202046327
        SubarrayDynamicEnergy_pJ: 543.4434794403141
      Write:
        DynamicEnergy_pJ: 7.846218577858443
      Leakage_mW: 10.349605895863313
TagArray:
  Configuration:
    BankOrganization:
      Rows: 1
      Columns: 1
      RowActivation: 1
      TotalRows: 1
      ColumnActivation: 1
      TotalColumns: 1
    MatOrganization:
      Rows: 2
      Columns: 2
      RowActivation: 1
      TotalRows: 2
      ColumnActivation: 1
      TotalColumns: 2
      SubarrayRows: 2048
      SubarrayColumns: 1920
    MuxLevels:
      SenseampMux: 1
      OutputLevel1Mux: 1
      OutputLevel2Mux: 8
      RowsPerSet: 1
    LocalWire:
      WireType: LocalAggressive
      RepeaterType: NoRepeaters
      LowSwing: No
    GlobalWire:
      WireType: GlobalAggressive
      RepeaterType: NoRepeaters
      LowSwing: No
    BufferDesignStyle: Balanced
  Results:
    Area:
      Total:
        Height_um: 1946.1185946207504
        Width_um: 1229.7920000000001
        Area_mm2: 2.393321078715842
      Mat:
        Height_um: 1946.1185946207504
        Width_um: 1229.7920000000001
        Area_mm2: 2.393321078715842
        Efficiency_percent: 98.25236636539032
      Subarray:
        Height_um: 963.2066
        Width_um: 614.8960000000001
        Area_mm2: 0.5922718855136
        Efficiency_percent: 99.25739563515059
      AreaEfficiency_percent: 98.25236636539032
    Timing:
      Read:
        Latency_ns: 59.038256263086254
        TreeLatency_ns: 0
        MatLatency_ns: 59.038256263086254
        PredecoderLatency_ns: 0.9746350939475715
        SubarrayLatency_ns: 57.85903816630388
        RowDecoderLatency_ns: 44.457719884802025
        BitlineLatency_ns: 13.364949505273849
        SenseampLatency_ns: 0.00602389339326742
        MuxLatency_ns: 0.030344882834740083
        PrechargeLatency_ns: 11.540124591964016
      Write:
        Latency_ns: 58.83367326025146
        TreeLatency_ns: 0
        MatLatency_ns: 58.83367326025146
        PredecoderLatency_ns: 0.9746350939475715
        SubarrayLatency_ns: 57.85903816630388
        RowDecoderLatency_ns: 44.457719884802025
        BitlineLatency_ns: 13.364949505273849
      ReadBandwidth_Bps: 150352167.63619813
      WriteBandwidth_Bps: 64812691.65279585
    Power:
      Read:
        DynamicEnergy_pJ: 132.69324648341745
        TreeDynamicEnergy_pJ: 0
        MatDynamicEnergy_pJ: 132.69324648341745
        SubarrayDynamicEnergy_pJ: 131.03776869336093
      Write:
        DynamicEnergy_pJ: 5.357199054118392
      Leakage_mW: 2.6559116152014948
