MemoryCell:
  MemoryCellType: MRAM (Magnetoresistive)
  CellArea_F2: 54
  CellArea_um2: 0.055296
  AspectRatio: 0.54
  R_on_KOhm: 3
  R_off_KOhm: 6
  ReadMode: Current-Sensing
  ReadVoltage_V: 0.25
  ResetMode: Current
  ResetVoltage_V: 0
  ResetCurrent_uA: 80
  ResetPulse_s: 1e-17
  SetMode: Current
  SetVoltage_V: 0
  SetCurrent_uA: 80
  SetPulse_s: 1e-17
  AccessType: CMOS
CacheDesign:
  AccessMode: Normal
  DesignTarget: Cache
  OptimizationTarget: WriteEDP
  Area:
    Total_mm2: 11.289849590106085
    DataArray_mm2: 8.89546486289717
    TagArray_mm2: 2.3943847272089145
  Timing:
    CacheHitLatency_ns: 7.126178902953784
    CacheMissLatency_ns: 3.2436527845992225
    CacheWriteLatency_ns: 13.592279528031195
    Reset:
      PulseDuration_ns: 10
    Set:
      PulseDuration_ns: 10
  Power:
    CacheHitDynamicEnergy_nJ: 0.29420417138375915
    CacheMissDynamicEnergy_nJ: 0.29420417138375915
    CacheWriteDynamicEnergy_nJ: 0.22303651379199652
    CacheTotalLeakagePower_mW: 30.33861665927605
    CacheDataArrayLeakagePower_mW: 18.25768351942296
    CacheTagArrayLeakagePower_mW: 12.080933139853085
Capacity:
  Value: 16
  Unit: MB
DataArray:
  Configuration:
    BankOrganization:
      Rows: 8
      Columns: 8
      RowActivation: 1
      TotalRows: 8
      ColumnActivation: 1
      TotalColumns: 8
    MatOrganization:
      Rows: 2
      Columns: 2
      RowActivation: 2
      TotalRows: 2
      ColumnActivation: 1
      TotalColumns: 2
      SubarrayRows: 1024
      SubarrayColumns: 512
    MuxLevels:
      SenseampMux: 1
      OutputLevel1Mux: 1
      OutputLevel2Mux: 1
      RowsPerSet: 1
    LocalWire:
      WireType: LocalAggressive
      RepeaterType: NoRepeaters
      LowSwing: No
    GlobalWire:
      WireType: GlobalAggressive
      RepeaterType: NoRepeaters
      LowSwing: No
    BufferDesignStyle: LatencyOptimized
  Results:
    Area:
      Total:
        Height_um: 3055.4079325170514
        Width_um: 2911.3837037037038
        Area_mm2: 8.89546486289717
      Mat:
        Height_um: 381.92599156463143
        Width_um: 363.92296296296297
        Area_mm2: 0.13899163848276827
        Efficiency_percent: 83.43244115823332
      Subarray:
        Height_um: 186.79270000000002
        Width_um: 181.96148148148148
        Area_mm2: 0.03398907642192593
        Efficiency_percent: 85.29513684960928
      AreaEfficiency_percent: 83.43244115823332
    Timing:
      Read:
        Latency_ns: 5.737966845635097
        TreeLatency_ns: 2.15293854023144
        MatLatency_ns: 3.5850283054036574
        PredecoderLatency_ns: 0.6134140692240065
        SubarrayLatency_ns: 2.9716142361796507
        RowDecoderLatency_ns: 1.6866271076152028
        BitlineLatency_ns: 0.19530730681047245
        SenseampLatency_ns: 1.07
        MuxLatency_ns: 0.01967982175397483
        PrechargeLatency_ns: 2.815120734422001
      Write:
        Latency_ns: 13.592279528031195
        TreeLatency_ns: 1.076469270115718
        MatLatency_ns: 12.515810257915478
        PredecoderLatency_ns: 0.6134140692240065
        SubarrayLatency_ns: 2.9716142361796507
        RowDecoderLatency_ns: 1.6866271076152028
        BitlineLatency_ns: 0.19530730681047245
      ReadBandwidth_Bps: 3902336361.5477843
      WriteBandwidth_Bps: 1344267132.9661908
    Power:
      Read:
        DynamicEnergy_pJ: 221.63376795463637
        TreeDynamicEnergy_pJ: 143.46717977799693
        MatDynamicEnergy_pJ: 78.16658817663945
        SubarrayDynamicEnergy_pJ: 38.967051529869885
      Write:
        DynamicEnergy_pJ: 164.63814293390928
      Leakage_mW: 18.25768351942296
TagArray:
  Configuration:
    BankOrganization:
      Rows: 8
      Columns: 8
      RowActivation: 1
      TotalRows: 8
      ColumnActivation: 1
      TotalColumns: 8
    MatOrganization:
      Rows: 2
      Columns: 2
      RowActivation: 1
      TotalRows: 2
      ColumnActivation: 1
      TotalColumns: 2
      SubarrayRows: 512
      SubarrayColumns: 232
    MuxLevels:
      SenseampMux: 1
      OutputLevel1Mux: 1
      OutputLevel2Mux: 1
      RowsPerSet: 1
    LocalWire:
      WireType: LocalAggressive
      RepeaterType: NoRepeaters
      LowSwing: No
    GlobalWire:
      WireType: GlobalAggressive
      RepeaterType: NoRepeaters
      LowSwing: No
    BufferDesignStyle: LatencyOptimized
  Results:
    Area:
      Total:
        Height_um: 1620.2538444617937
        Width_um: 1477.7837037037038
        Area_mm2: 2.3943847272089145
      Mat:
        Height_um: 202.53173055772422
        Width_um: 184.72296296296298
        Area_mm2: 0.03741226136263929
        Efficiency_percent: 70.22596148715277
      Subarray:
        Height_um: 95.2562551724138
        Width_um: 92.36148148148149
        Area_mm2: 0.008798008848102171
        Efficiency_percent: 74.65643848967997
      AreaEfficiency_percent: 70.22596148715277
    Timing:
      Read:
        Latency_ns: 3.2436527845992225
        TreeLatency_ns: 0.5656475068460508
        MatLatency_ns: 2.6780052777531713
        PredecoderLatency_ns: 0.5984802412642378
        SubarrayLatency_ns: 1.874942033654134
        RowDecoderLatency_ns: 0.7524045576364675
        BitlineLatency_ns: 0.05253747601766646
        SenseampLatency_ns: 1.07
        MuxLatency_ns: 0
        PrechargeLatency_ns: 1.361287609824332
      Write:
        Latency_ns: 11.633708552323732
        TreeLatency_ns: 0.2828237534230264
        MatLatency_ns: 11.350884798900704
        PredecoderLatency_ns: 0.5984802412642378
        SubarrayLatency_ns: 1.874942033654134
        RowDecoderLatency_ns: 0.7524045576364675
        BitlineLatency_ns: 0.05253747601766646
      ReadBandwidth_Bps: 1459442543.1415398
      WriteBandwidth_Bps: 337133892.29067725
    Power:
      Read:
        DynamicEnergy_pJ: 72.57040342912276
        TreeDynamicEnergy_pJ: 26.49758557795169
        MatDynamicEnergy_pJ: 46.072817851171074
        SubarrayDynamicEnergy_pJ: 45.10599534120625
      Write:
        DynamicEnergy_pJ: 58.39837085808723
      Leakage_mW: 12.080933139853085
