MemoryCell:
  MemoryCellType: MRAM (Magnetoresistive)
  CellArea_F2: 54
  CellArea_um2: 0.055296
  AspectRatio: 0.54
  R_on_KOhm: 3
  R_off_KOhm: 6
  ReadMode: Current-Sensing
  ReadVoltage_V: 0.25
  ResetMode: Current
  ResetVoltage_V: 0
  ResetCurrent_uA: 80
  ResetPulse_s: 1e-17
  SetMode: Current
  SetVoltage_V: 0
  SetCurrent_uA: 80
  SetPulse_s: 1e-17
  AccessType: CMOS
CacheDesign:
  AccessMode: Normal
  DesignTarget: Cache
  OptimizationTarget: WriteDynamicEnergy
  Area:
    Total_mm2: 4.78021818323573
    DataArray_mm2: 3.8602640803070174
    TagArray_mm2: 0.9199541029287128
  Timing:
    CacheHitLatency_ns: 130.0161393366112
    CacheMissLatency_ns: 116.54421613212779
    CacheWriteLatency_ns: 123.64042609355063
    Reset:
      PulseDuration_ns: 10
    Set:
      PulseDuration_ns: 10
  Power:
    CacheHitDynamicEnergy_nJ: 0.37003332620436635
    CacheMissDynamicEnergy_nJ: 0.37003332620436635
    CacheWriteDynamicEnergy_nJ: 0.07433299427188697
    CacheTotalLeakagePower_mW: 3.9054937435614123
    CacheDataArrayLeakagePower_mW: 0.9770756577196732
    CacheTagArrayLeakagePower_mW: 2.928418085841739
Capacity:
  Value: 8
  Unit: MB
DataArray:
  Configuration:
    BankOrganization:
      Rows: 1
      Columns: 1
      RowActivation: 1
      TotalRows: 1
      ColumnActivation: 1
      TotalColumns: 1
    MatOrganization:
      Rows: 2
      Columns: 2
      RowActivation: 1
      TotalRows: 2
      ColumnActivation: 1
      TotalColumns: 2
      SubarrayRows: 8192
      SubarrayColumns: 2048
    MuxLevels:
      SenseampMux: 2
      OutputLevel1Mux: 1
      OutputLevel2Mux: 1
      RowsPerSet: 1
    LocalWire:
      WireType: LocalAggressive
      RepeaterType: NoRepeaters
      LowSwing: No
    GlobalWire:
      WireType: GlobalAggressive
      RepeaterType: NoRepeaters
      LowSwing: No
    BufferDesignStyle: LatencyOptimized
  Results:
    Area:
      Total:
        Height_um: 2865.9021713673965
        Width_um: 1346.962962962963
        Area_mm2: 3.8602640803070174
      Mat:
        Height_um: 2865.9021713673965
        Width_um: 1346.962962962963
        Area_mm2: 3.8602640803070174
        Efficiency_percent: 96.12947887878349
      Subarray:
        Height_um: 1424.948725
        Width_um: 673.4814814814815
        Area_mm2: 0.9596765783481481
        Efficiency_percent: 96.66933182143865
      AreaEfficiency_percent: 96.12947887878349
    Timing:
      Read:
        Latency_ns: 26.465879825228992
        TreeLatency_ns: 0
        MatLatency_ns: 26.465879825228992
        PredecoderLatency_ns: 1.10105633961718
        SubarrayLatency_ns: 25.364823485611808
        RowDecoderLatency_ns: 16.401555024325944
        BitlineLatency_ns: 7.869938022199265
        SenseampLatency_ns: 1.07
        MuxLatency_ns: 0.023330439086604156
        PrechargeLatency_ns: 35.161367717924875
      Write:
        Latency_ns: 41.487841450339054
        TreeLatency_ns: 0
        MatLatency_ns: 41.487841450339054
        PredecoderLatency_ns: 1.10105633961718
        SubarrayLatency_ns: 25.364823485611808
        RowDecoderLatency_ns: 16.401555024325944
        BitlineLatency_ns: 7.869938022199265
      ReadBandwidth_Bps: 362609222.0911813
      WriteBandwidth_Bps: 396169191.386128
    Power:
      Read:
        DynamicEnergy_pJ: 102.74313488813002
        TreeDynamicEnergy_pJ: 0
        MatDynamicEnergy_pJ: 102.74313488813002
        SubarrayDynamicEnergy_pJ: 101.67283719609053
      Write:
        DynamicEnergy_pJ: 34.25042291106524
      Leakage_mW: 0.9770756577196732
TagArray:
  Configuration:
    BankOrganization:
      Rows: 2
      Columns: 1
      RowActivation: 1
      TotalRows: 2
      ColumnActivation: 1
      TotalColumns: 1
    MatOrganization:
      Rows: 2
      Columns: 2
      RowActivation: 1
      TotalRows: 2
      ColumnActivation: 1
      TotalColumns: 2
      SubarrayRows: 1024
      SubarrayColumns: 1920
    MuxLevels:
      SenseampMux: 1
      OutputLevel1Mux: 1
      OutputLevel2Mux: 8
      RowsPerSet: 1
    LocalWire:
      WireType: LocalAggressive
      RepeaterType: NoRepeaters
      LowSwing: No
    GlobalWire:
      WireType: GlobalAggressive
      RepeaterType: NoRepeaters
      LowSwing: Yes
    BufferDesignStyle: Balanced
  Results:
    Area:
      Total:
        Height_um: 737.7908235213058
        Width_um: 1246.903693567214
        Area_mm2: 0.9199541029287128
      Mat:
        Height_um: 368.8954117606529
        Width_um: 1246.903693567214
        Area_mm2: 0.4599770514643564
        Efficiency_percent: 94.54068139607999
      Subarray:
        Height_um: 184.40353333333334
        Width_um: 615.4334022222223
        Area_mm2: 0.11348809390113232
        Efficiency_percent: 95.79538781813596
      AreaEfficiency_percent: 94.54068139607999
    Timing:
      Read:
        Latency_ns: 116.54421613212779
        TreeLatency_ns: 2.8380404886191495
        MatLatency_ns: 113.70617564350864
        PredecoderLatency_ns: 0.7709293530185646
        SubarrayLatency_ns: 112.73066328765528
        RowDecoderLatency_ns: 111.45047649622249
        BitlineLatency_ns: 0.19530730681047245
        SenseampLatency_ns: 1.07
        MuxLatency_ns: 0.014879484622323079
        PrechargeLatency_ns: 2.831652196196363
      Write:
        Latency_ns: 123.64042609355063
        TreeLatency_ns: 1.419020244309568
        MatLatency_ns: 122.22140584924107
        PredecoderLatency_ns: 0.7709293530185646
        SubarrayLatency_ns: 112.73066328765528
        RowDecoderLatency_ns: 111.45047649622249
        BitlineLatency_ns: 0.19530730681047245
      ReadBandwidth_Bps: 912000691.4867591
      WriteBandwidth_Bps: 30876782.933961045
    Power:
      Read:
        DynamicEnergy_pJ: 267.2901913162363
        TreeDynamicEnergy_pJ: 0.9965317538732209
        MatDynamicEnergy_pJ: 266.2936595623631
        SubarrayDynamicEnergy_pJ: 264.99880813255254
      Write:
        DynamicEnergy_pJ: 40.08257136082174
      Leakage_mW: 2.928418085841739
